#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

check_subdomain() {
local domain=$1
local subdomain=$2

local result
result=$(dig @tech-domains.earth.orderbox-dns.com "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4, $5}')

local record_type
local destination
record_type=$(echo $result | awk '{print $1}')
destination=$(echo $result | awk '{print $2}')

echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
check_subdomain "$domain" "www"
check_subdomain "$domain" "lb-01"
check_subdomain "$domain" "web-01"
check_subdomain "$domain" "web-02"
else
check_subdomain "$domain" "$subdomain"
fi
